# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
# or https://canovasjm.netlify.app/2020/11/29/github-actions-run-a-python-script-on-schedule-and-commit-changes/

name: twitterbot

on:
  schedule:
    - cron: '0 14 * * *' # runs at 12:00 UTC everyday

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: execute py script
      env:
        consumer_key: ${{ secrets.consumer_key }}
        consumer_secret: ${{ secrets.consumer_secret }}
        access_token_secret: ${{ secrets.access_token_secret }}
        access_token: ${{ secrets.access_token }}
      run: python tweet.py
