# This is a basic workflow to help you get started with Actions

name: twitterbot

# Controls when the workflow will run
on:
  schedule:
    #- cron: '0 14 * * *' # runs at 12:00 UTC everyday
    - cron: '*/10 * * * *' # run every 10 minutes

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2

      - name: Set up Python 🐍
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Cache Python packages 💾
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
            
      - name: Install packages ⚙
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: execute py script
        env:
          consumer_key: ${{ secrets.consumer_key }}
          consumer_secret: ${{ secrets.consumer_secret }}
          access_token_secret: ${{ secrets.access_token_secret }}
          access_token: ${{ secrets.access_token }}
        run: | 
          python tweet.py
